/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FpAmbulanceWlList {
    }
}
declare global {
    interface HTMLFpAmbulanceWlListElement extends Components.FpAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLFpAmbulanceWlListElement: {
        prototype: HTMLFpAmbulanceWlListElement;
        new (): HTMLFpAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "fp-ambulance-wl-list": HTMLFpAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface FpAmbulanceWlList {
    }
    interface IntrinsicElements {
        "fp-ambulance-wl-list": FpAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fp-ambulance-wl-list": LocalJSX.FpAmbulanceWlList & JSXBase.HTMLAttributes<HTMLFpAmbulanceWlListElement>;
        }
    }
}
